MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  # NAME: 'RN50'
  STRIDE_SIZE: [16, 16]
  ID_LOSS_WEIGHT : 1.0
  TRIPLET_LOSS_WEIGHT : 1.0
  SIE_CAMERA: True
  SIE_COE : 1.0

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  SEQ_LEN: 8

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  MARGIN: 0.3
  IMS_PER_BATCH: 16
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.000005
  WARMUP_METHOD: 'linear'
  WARMUP_ITERS: 10
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY:  0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  LARGE_FC_LR: True
  LARGE_Prompt_LR: True
  MAX_EPOCHS: 300
  CHECKPOINT_PERIOD: 60
  LOG_PERIOD: 50
  EVAL_PERIOD: 10
  BIAS_LR_FACTOR: 2

  STEPS: []
  GAMMA: 0.1
  
TEST:
  EVAL: False
  IMS_PER_BATCH: 1
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

DATASETS:
  NAMES: ('mars')
  ROOT_DIR: ('../datasets/reid/MARS')

OUTPUT_DIR: 'output/mars/SORSNet'
few_shot_n: 1